################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Source_include/arm_bartlett_f32.c \
../Source_include/arm_bartlett_f64.c \
../Source_include/arm_bitreversal.c \
../Source_include/arm_bitreversal2.c \
../Source_include/arm_bitreversal_f16.c \
../Source_include/arm_blackman_harris_92db_f32.c \
../Source_include/arm_blackman_harris_92db_f64.c \
../Source_include/arm_cfft_f16.c \
../Source_include/arm_cfft_f32.c \
../Source_include/arm_cfft_f64.c \
../Source_include/arm_cfft_init_f16.c \
../Source_include/arm_cfft_init_f32.c \
../Source_include/arm_cfft_init_f64.c \
../Source_include/arm_cfft_init_q15.c \
../Source_include/arm_cfft_init_q31.c \
../Source_include/arm_cfft_q15.c \
../Source_include/arm_cfft_q31.c \
../Source_include/arm_cfft_radix2_f16.c \
../Source_include/arm_cfft_radix2_f32.c \
../Source_include/arm_cfft_radix2_init_f16.c \
../Source_include/arm_cfft_radix2_init_f32.c \
../Source_include/arm_cfft_radix2_init_q15.c \
../Source_include/arm_cfft_radix2_init_q31.c \
../Source_include/arm_cfft_radix2_q15.c \
../Source_include/arm_cfft_radix2_q31.c \
../Source_include/arm_cfft_radix4_f16.c \
../Source_include/arm_cfft_radix4_f32.c \
../Source_include/arm_cfft_radix4_init_f16.c \
../Source_include/arm_cfft_radix4_init_f32.c \
../Source_include/arm_cfft_radix4_init_q15.c \
../Source_include/arm_cfft_radix4_init_q31.c \
../Source_include/arm_cfft_radix4_q15.c \
../Source_include/arm_cfft_radix4_q31.c \
../Source_include/arm_cfft_radix8_f16.c \
../Source_include/arm_cfft_radix8_f32.c \
../Source_include/arm_dct4_f32.c \
../Source_include/arm_dct4_init_f32.c \
../Source_include/arm_dct4_init_q15.c \
../Source_include/arm_dct4_init_q31.c \
../Source_include/arm_dct4_q15.c \
../Source_include/arm_dct4_q31.c \
../Source_include/arm_hamming_f32.c \
../Source_include/arm_hamming_f64.c \
../Source_include/arm_hanning_f32.c \
../Source_include/arm_hanning_f64.c \
../Source_include/arm_hft116d_f32.c \
../Source_include/arm_hft116d_f64.c \
../Source_include/arm_hft144d_f32.c \
../Source_include/arm_hft144d_f64.c \
../Source_include/arm_hft169d_f32.c \
../Source_include/arm_hft169d_f64.c \
../Source_include/arm_hft196d_f32.c \
../Source_include/arm_hft196d_f64.c \
../Source_include/arm_hft223d_f32.c \
../Source_include/arm_hft223d_f64.c \
../Source_include/arm_hft248d_f32.c \
../Source_include/arm_hft248d_f64.c \
../Source_include/arm_hft90d_f32.c \
../Source_include/arm_hft90d_f64.c \
../Source_include/arm_hft95_f32.c \
../Source_include/arm_hft95_f64.c \
../Source_include/arm_mfcc_f16.c \
../Source_include/arm_mfcc_f32.c \
../Source_include/arm_mfcc_init_f16.c \
../Source_include/arm_mfcc_init_f32.c \
../Source_include/arm_mfcc_init_q15.c \
../Source_include/arm_mfcc_init_q31.c \
../Source_include/arm_mfcc_q15.c \
../Source_include/arm_mfcc_q31.c \
../Source_include/arm_nuttall3_f32.c \
../Source_include/arm_nuttall3_f64.c \
../Source_include/arm_nuttall3a_f32.c \
../Source_include/arm_nuttall3a_f64.c \
../Source_include/arm_nuttall3b_f32.c \
../Source_include/arm_nuttall3b_f64.c \
../Source_include/arm_nuttall4_f32.c \
../Source_include/arm_nuttall4_f64.c \
../Source_include/arm_nuttall4a_f32.c \
../Source_include/arm_nuttall4a_f64.c \
../Source_include/arm_nuttall4b_f32.c \
../Source_include/arm_nuttall4b_f64.c \
../Source_include/arm_nuttall4c_f32.c \
../Source_include/arm_nuttall4c_f64.c \
../Source_include/arm_rfft_f32.c \
../Source_include/arm_rfft_fast_f16.c \
../Source_include/arm_rfft_fast_f32.c \
../Source_include/arm_rfft_fast_f64.c \
../Source_include/arm_rfft_fast_init_f16.c \
../Source_include/arm_rfft_fast_init_f32.c \
../Source_include/arm_rfft_fast_init_f64.c \
../Source_include/arm_rfft_init_f32.c \
../Source_include/arm_rfft_init_q15.c \
../Source_include/arm_rfft_init_q31.c \
../Source_include/arm_rfft_q15.c \
../Source_include/arm_rfft_q31.c \
../Source_include/arm_svm_linear_init_f32.c \
../Source_include/arm_svm_linear_predict_f32.c \
../Source_include/arm_svm_polynomial_init_f32.c \
../Source_include/arm_svm_polynomial_predict_f32.c \
../Source_include/arm_svm_rbf_init_f32.c \
../Source_include/arm_svm_rbf_predict_f32.c \
../Source_include/arm_svm_sigmoid_init_f32.c \
../Source_include/arm_svm_sigmoid_predict_f32.c \
../Source_include/arm_welch_f32.c \
../Source_include/arm_welch_f64.c 

OBJS += \
./Source_include/arm_bartlett_f32.o \
./Source_include/arm_bartlett_f64.o \
./Source_include/arm_bitreversal.o \
./Source_include/arm_bitreversal2.o \
./Source_include/arm_bitreversal_f16.o \
./Source_include/arm_blackman_harris_92db_f32.o \
./Source_include/arm_blackman_harris_92db_f64.o \
./Source_include/arm_cfft_f16.o \
./Source_include/arm_cfft_f32.o \
./Source_include/arm_cfft_f64.o \
./Source_include/arm_cfft_init_f16.o \
./Source_include/arm_cfft_init_f32.o \
./Source_include/arm_cfft_init_f64.o \
./Source_include/arm_cfft_init_q15.o \
./Source_include/arm_cfft_init_q31.o \
./Source_include/arm_cfft_q15.o \
./Source_include/arm_cfft_q31.o \
./Source_include/arm_cfft_radix2_f16.o \
./Source_include/arm_cfft_radix2_f32.o \
./Source_include/arm_cfft_radix2_init_f16.o \
./Source_include/arm_cfft_radix2_init_f32.o \
./Source_include/arm_cfft_radix2_init_q15.o \
./Source_include/arm_cfft_radix2_init_q31.o \
./Source_include/arm_cfft_radix2_q15.o \
./Source_include/arm_cfft_radix2_q31.o \
./Source_include/arm_cfft_radix4_f16.o \
./Source_include/arm_cfft_radix4_f32.o \
./Source_include/arm_cfft_radix4_init_f16.o \
./Source_include/arm_cfft_radix4_init_f32.o \
./Source_include/arm_cfft_radix4_init_q15.o \
./Source_include/arm_cfft_radix4_init_q31.o \
./Source_include/arm_cfft_radix4_q15.o \
./Source_include/arm_cfft_radix4_q31.o \
./Source_include/arm_cfft_radix8_f16.o \
./Source_include/arm_cfft_radix8_f32.o \
./Source_include/arm_dct4_f32.o \
./Source_include/arm_dct4_init_f32.o \
./Source_include/arm_dct4_init_q15.o \
./Source_include/arm_dct4_init_q31.o \
./Source_include/arm_dct4_q15.o \
./Source_include/arm_dct4_q31.o \
./Source_include/arm_hamming_f32.o \
./Source_include/arm_hamming_f64.o \
./Source_include/arm_hanning_f32.o \
./Source_include/arm_hanning_f64.o \
./Source_include/arm_hft116d_f32.o \
./Source_include/arm_hft116d_f64.o \
./Source_include/arm_hft144d_f32.o \
./Source_include/arm_hft144d_f64.o \
./Source_include/arm_hft169d_f32.o \
./Source_include/arm_hft169d_f64.o \
./Source_include/arm_hft196d_f32.o \
./Source_include/arm_hft196d_f64.o \
./Source_include/arm_hft223d_f32.o \
./Source_include/arm_hft223d_f64.o \
./Source_include/arm_hft248d_f32.o \
./Source_include/arm_hft248d_f64.o \
./Source_include/arm_hft90d_f32.o \
./Source_include/arm_hft90d_f64.o \
./Source_include/arm_hft95_f32.o \
./Source_include/arm_hft95_f64.o \
./Source_include/arm_mfcc_f16.o \
./Source_include/arm_mfcc_f32.o \
./Source_include/arm_mfcc_init_f16.o \
./Source_include/arm_mfcc_init_f32.o \
./Source_include/arm_mfcc_init_q15.o \
./Source_include/arm_mfcc_init_q31.o \
./Source_include/arm_mfcc_q15.o \
./Source_include/arm_mfcc_q31.o \
./Source_include/arm_nuttall3_f32.o \
./Source_include/arm_nuttall3_f64.o \
./Source_include/arm_nuttall3a_f32.o \
./Source_include/arm_nuttall3a_f64.o \
./Source_include/arm_nuttall3b_f32.o \
./Source_include/arm_nuttall3b_f64.o \
./Source_include/arm_nuttall4_f32.o \
./Source_include/arm_nuttall4_f64.o \
./Source_include/arm_nuttall4a_f32.o \
./Source_include/arm_nuttall4a_f64.o \
./Source_include/arm_nuttall4b_f32.o \
./Source_include/arm_nuttall4b_f64.o \
./Source_include/arm_nuttall4c_f32.o \
./Source_include/arm_nuttall4c_f64.o \
./Source_include/arm_rfft_f32.o \
./Source_include/arm_rfft_fast_f16.o \
./Source_include/arm_rfft_fast_f32.o \
./Source_include/arm_rfft_fast_f64.o \
./Source_include/arm_rfft_fast_init_f16.o \
./Source_include/arm_rfft_fast_init_f32.o \
./Source_include/arm_rfft_fast_init_f64.o \
./Source_include/arm_rfft_init_f32.o \
./Source_include/arm_rfft_init_q15.o \
./Source_include/arm_rfft_init_q31.o \
./Source_include/arm_rfft_q15.o \
./Source_include/arm_rfft_q31.o \
./Source_include/arm_svm_linear_init_f32.o \
./Source_include/arm_svm_linear_predict_f32.o \
./Source_include/arm_svm_polynomial_init_f32.o \
./Source_include/arm_svm_polynomial_predict_f32.o \
./Source_include/arm_svm_rbf_init_f32.o \
./Source_include/arm_svm_rbf_predict_f32.o \
./Source_include/arm_svm_sigmoid_init_f32.o \
./Source_include/arm_svm_sigmoid_predict_f32.o \
./Source_include/arm_welch_f32.o \
./Source_include/arm_welch_f64.o 

C_DEPS += \
./Source_include/arm_bartlett_f32.d \
./Source_include/arm_bartlett_f64.d \
./Source_include/arm_bitreversal.d \
./Source_include/arm_bitreversal2.d \
./Source_include/arm_bitreversal_f16.d \
./Source_include/arm_blackman_harris_92db_f32.d \
./Source_include/arm_blackman_harris_92db_f64.d \
./Source_include/arm_cfft_f16.d \
./Source_include/arm_cfft_f32.d \
./Source_include/arm_cfft_f64.d \
./Source_include/arm_cfft_init_f16.d \
./Source_include/arm_cfft_init_f32.d \
./Source_include/arm_cfft_init_f64.d \
./Source_include/arm_cfft_init_q15.d \
./Source_include/arm_cfft_init_q31.d \
./Source_include/arm_cfft_q15.d \
./Source_include/arm_cfft_q31.d \
./Source_include/arm_cfft_radix2_f16.d \
./Source_include/arm_cfft_radix2_f32.d \
./Source_include/arm_cfft_radix2_init_f16.d \
./Source_include/arm_cfft_radix2_init_f32.d \
./Source_include/arm_cfft_radix2_init_q15.d \
./Source_include/arm_cfft_radix2_init_q31.d \
./Source_include/arm_cfft_radix2_q15.d \
./Source_include/arm_cfft_radix2_q31.d \
./Source_include/arm_cfft_radix4_f16.d \
./Source_include/arm_cfft_radix4_f32.d \
./Source_include/arm_cfft_radix4_init_f16.d \
./Source_include/arm_cfft_radix4_init_f32.d \
./Source_include/arm_cfft_radix4_init_q15.d \
./Source_include/arm_cfft_radix4_init_q31.d \
./Source_include/arm_cfft_radix4_q15.d \
./Source_include/arm_cfft_radix4_q31.d \
./Source_include/arm_cfft_radix8_f16.d \
./Source_include/arm_cfft_radix8_f32.d \
./Source_include/arm_dct4_f32.d \
./Source_include/arm_dct4_init_f32.d \
./Source_include/arm_dct4_init_q15.d \
./Source_include/arm_dct4_init_q31.d \
./Source_include/arm_dct4_q15.d \
./Source_include/arm_dct4_q31.d \
./Source_include/arm_hamming_f32.d \
./Source_include/arm_hamming_f64.d \
./Source_include/arm_hanning_f32.d \
./Source_include/arm_hanning_f64.d \
./Source_include/arm_hft116d_f32.d \
./Source_include/arm_hft116d_f64.d \
./Source_include/arm_hft144d_f32.d \
./Source_include/arm_hft144d_f64.d \
./Source_include/arm_hft169d_f32.d \
./Source_include/arm_hft169d_f64.d \
./Source_include/arm_hft196d_f32.d \
./Source_include/arm_hft196d_f64.d \
./Source_include/arm_hft223d_f32.d \
./Source_include/arm_hft223d_f64.d \
./Source_include/arm_hft248d_f32.d \
./Source_include/arm_hft248d_f64.d \
./Source_include/arm_hft90d_f32.d \
./Source_include/arm_hft90d_f64.d \
./Source_include/arm_hft95_f32.d \
./Source_include/arm_hft95_f64.d \
./Source_include/arm_mfcc_f16.d \
./Source_include/arm_mfcc_f32.d \
./Source_include/arm_mfcc_init_f16.d \
./Source_include/arm_mfcc_init_f32.d \
./Source_include/arm_mfcc_init_q15.d \
./Source_include/arm_mfcc_init_q31.d \
./Source_include/arm_mfcc_q15.d \
./Source_include/arm_mfcc_q31.d \
./Source_include/arm_nuttall3_f32.d \
./Source_include/arm_nuttall3_f64.d \
./Source_include/arm_nuttall3a_f32.d \
./Source_include/arm_nuttall3a_f64.d \
./Source_include/arm_nuttall3b_f32.d \
./Source_include/arm_nuttall3b_f64.d \
./Source_include/arm_nuttall4_f32.d \
./Source_include/arm_nuttall4_f64.d \
./Source_include/arm_nuttall4a_f32.d \
./Source_include/arm_nuttall4a_f64.d \
./Source_include/arm_nuttall4b_f32.d \
./Source_include/arm_nuttall4b_f64.d \
./Source_include/arm_nuttall4c_f32.d \
./Source_include/arm_nuttall4c_f64.d \
./Source_include/arm_rfft_f32.d \
./Source_include/arm_rfft_fast_f16.d \
./Source_include/arm_rfft_fast_f32.d \
./Source_include/arm_rfft_fast_f64.d \
./Source_include/arm_rfft_fast_init_f16.d \
./Source_include/arm_rfft_fast_init_f32.d \
./Source_include/arm_rfft_fast_init_f64.d \
./Source_include/arm_rfft_init_f32.d \
./Source_include/arm_rfft_init_q15.d \
./Source_include/arm_rfft_init_q31.d \
./Source_include/arm_rfft_q15.d \
./Source_include/arm_rfft_q31.d \
./Source_include/arm_svm_linear_init_f32.d \
./Source_include/arm_svm_linear_predict_f32.d \
./Source_include/arm_svm_polynomial_init_f32.d \
./Source_include/arm_svm_polynomial_predict_f32.d \
./Source_include/arm_svm_rbf_init_f32.d \
./Source_include/arm_svm_rbf_predict_f32.d \
./Source_include/arm_svm_sigmoid_init_f32.d \
./Source_include/arm_svm_sigmoid_predict_f32.d \
./Source_include/arm_welch_f32.d \
./Source_include/arm_welch_f64.d 


# Each subdirectory must supply rules for building sources it contributes
Source_include/%.o Source_include/%.su Source_include/%.cyclo: ../Source_include/%.c Source_include/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g -DDEBUG -DUSE_HAL_DRIVER -DSTM32L476xx -c -I../Core/Inc -I"/home/Bartosz/Desktop/MicrocontrollerLaboratories/Laboratory10/blank_dsp_project/Source_include" -I"/home/Bartosz/Desktop/MicrocontrollerLaboratories/Laboratory10/blank_dsp_project/Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/ARM_CMSIS/PrivateInclude/ -I../Middlewares/Third_Party/ARM_CMSIS/Include/ -I../Middlewares/Third_Party/ARM_CMSIS/Include -I../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Source_include

clean-Source_include:
	-$(RM) ./Source_include/arm_bartlett_f32.cyclo ./Source_include/arm_bartlett_f32.d ./Source_include/arm_bartlett_f32.o ./Source_include/arm_bartlett_f32.su ./Source_include/arm_bartlett_f64.cyclo ./Source_include/arm_bartlett_f64.d ./Source_include/arm_bartlett_f64.o ./Source_include/arm_bartlett_f64.su ./Source_include/arm_bitreversal.cyclo ./Source_include/arm_bitreversal.d ./Source_include/arm_bitreversal.o ./Source_include/arm_bitreversal.su ./Source_include/arm_bitreversal2.cyclo ./Source_include/arm_bitreversal2.d ./Source_include/arm_bitreversal2.o ./Source_include/arm_bitreversal2.su ./Source_include/arm_bitreversal_f16.cyclo ./Source_include/arm_bitreversal_f16.d ./Source_include/arm_bitreversal_f16.o ./Source_include/arm_bitreversal_f16.su ./Source_include/arm_blackman_harris_92db_f32.cyclo ./Source_include/arm_blackman_harris_92db_f32.d ./Source_include/arm_blackman_harris_92db_f32.o ./Source_include/arm_blackman_harris_92db_f32.su ./Source_include/arm_blackman_harris_92db_f64.cyclo ./Source_include/arm_blackman_harris_92db_f64.d ./Source_include/arm_blackman_harris_92db_f64.o ./Source_include/arm_blackman_harris_92db_f64.su ./Source_include/arm_cfft_f16.cyclo ./Source_include/arm_cfft_f16.d ./Source_include/arm_cfft_f16.o ./Source_include/arm_cfft_f16.su ./Source_include/arm_cfft_f32.cyclo ./Source_include/arm_cfft_f32.d ./Source_include/arm_cfft_f32.o ./Source_include/arm_cfft_f32.su ./Source_include/arm_cfft_f64.cyclo ./Source_include/arm_cfft_f64.d ./Source_include/arm_cfft_f64.o ./Source_include/arm_cfft_f64.su ./Source_include/arm_cfft_init_f16.cyclo ./Source_include/arm_cfft_init_f16.d ./Source_include/arm_cfft_init_f16.o ./Source_include/arm_cfft_init_f16.su ./Source_include/arm_cfft_init_f32.cyclo ./Source_include/arm_cfft_init_f32.d ./Source_include/arm_cfft_init_f32.o ./Source_include/arm_cfft_init_f32.su ./Source_include/arm_cfft_init_f64.cyclo ./Source_include/arm_cfft_init_f64.d ./Source_include/arm_cfft_init_f64.o ./Source_include/arm_cfft_init_f64.su ./Source_include/arm_cfft_init_q15.cyclo ./Source_include/arm_cfft_init_q15.d ./Source_include/arm_cfft_init_q15.o ./Source_include/arm_cfft_init_q15.su ./Source_include/arm_cfft_init_q31.cyclo ./Source_include/arm_cfft_init_q31.d ./Source_include/arm_cfft_init_q31.o ./Source_include/arm_cfft_init_q31.su ./Source_include/arm_cfft_q15.cyclo ./Source_include/arm_cfft_q15.d ./Source_include/arm_cfft_q15.o ./Source_include/arm_cfft_q15.su ./Source_include/arm_cfft_q31.cyclo ./Source_include/arm_cfft_q31.d ./Source_include/arm_cfft_q31.o ./Source_include/arm_cfft_q31.su ./Source_include/arm_cfft_radix2_f16.cyclo ./Source_include/arm_cfft_radix2_f16.d ./Source_include/arm_cfft_radix2_f16.o ./Source_include/arm_cfft_radix2_f16.su ./Source_include/arm_cfft_radix2_f32.cyclo ./Source_include/arm_cfft_radix2_f32.d ./Source_include/arm_cfft_radix2_f32.o ./Source_include/arm_cfft_radix2_f32.su ./Source_include/arm_cfft_radix2_init_f16.cyclo ./Source_include/arm_cfft_radix2_init_f16.d ./Source_include/arm_cfft_radix2_init_f16.o ./Source_include/arm_cfft_radix2_init_f16.su ./Source_include/arm_cfft_radix2_init_f32.cyclo ./Source_include/arm_cfft_radix2_init_f32.d ./Source_include/arm_cfft_radix2_init_f32.o ./Source_include/arm_cfft_radix2_init_f32.su ./Source_include/arm_cfft_radix2_init_q15.cyclo ./Source_include/arm_cfft_radix2_init_q15.d ./Source_include/arm_cfft_radix2_init_q15.o ./Source_include/arm_cfft_radix2_init_q15.su ./Source_include/arm_cfft_radix2_init_q31.cyclo ./Source_include/arm_cfft_radix2_init_q31.d ./Source_include/arm_cfft_radix2_init_q31.o ./Source_include/arm_cfft_radix2_init_q31.su ./Source_include/arm_cfft_radix2_q15.cyclo ./Source_include/arm_cfft_radix2_q15.d ./Source_include/arm_cfft_radix2_q15.o ./Source_include/arm_cfft_radix2_q15.su ./Source_include/arm_cfft_radix2_q31.cyclo ./Source_include/arm_cfft_radix2_q31.d ./Source_include/arm_cfft_radix2_q31.o ./Source_include/arm_cfft_radix2_q31.su ./Source_include/arm_cfft_radix4_f16.cyclo ./Source_include/arm_cfft_radix4_f16.d ./Source_include/arm_cfft_radix4_f16.o ./Source_include/arm_cfft_radix4_f16.su ./Source_include/arm_cfft_radix4_f32.cyclo ./Source_include/arm_cfft_radix4_f32.d ./Source_include/arm_cfft_radix4_f32.o ./Source_include/arm_cfft_radix4_f32.su ./Source_include/arm_cfft_radix4_init_f16.cyclo ./Source_include/arm_cfft_radix4_init_f16.d ./Source_include/arm_cfft_radix4_init_f16.o ./Source_include/arm_cfft_radix4_init_f16.su ./Source_include/arm_cfft_radix4_init_f32.cyclo ./Source_include/arm_cfft_radix4_init_f32.d ./Source_include/arm_cfft_radix4_init_f32.o ./Source_include/arm_cfft_radix4_init_f32.su ./Source_include/arm_cfft_radix4_init_q15.cyclo ./Source_include/arm_cfft_radix4_init_q15.d ./Source_include/arm_cfft_radix4_init_q15.o ./Source_include/arm_cfft_radix4_init_q15.su ./Source_include/arm_cfft_radix4_init_q31.cyclo ./Source_include/arm_cfft_radix4_init_q31.d ./Source_include/arm_cfft_radix4_init_q31.o ./Source_include/arm_cfft_radix4_init_q31.su ./Source_include/arm_cfft_radix4_q15.cyclo ./Source_include/arm_cfft_radix4_q15.d ./Source_include/arm_cfft_radix4_q15.o ./Source_include/arm_cfft_radix4_q15.su ./Source_include/arm_cfft_radix4_q31.cyclo ./Source_include/arm_cfft_radix4_q31.d ./Source_include/arm_cfft_radix4_q31.o ./Source_include/arm_cfft_radix4_q31.su ./Source_include/arm_cfft_radix8_f16.cyclo ./Source_include/arm_cfft_radix8_f16.d ./Source_include/arm_cfft_radix8_f16.o ./Source_include/arm_cfft_radix8_f16.su ./Source_include/arm_cfft_radix8_f32.cyclo ./Source_include/arm_cfft_radix8_f32.d ./Source_include/arm_cfft_radix8_f32.o ./Source_include/arm_cfft_radix8_f32.su ./Source_include/arm_dct4_f32.cyclo ./Source_include/arm_dct4_f32.d ./Source_include/arm_dct4_f32.o ./Source_include/arm_dct4_f32.su ./Source_include/arm_dct4_init_f32.cyclo ./Source_include/arm_dct4_init_f32.d ./Source_include/arm_dct4_init_f32.o ./Source_include/arm_dct4_init_f32.su ./Source_include/arm_dct4_init_q15.cyclo
	-$(RM) ./Source_include/arm_dct4_init_q15.d ./Source_include/arm_dct4_init_q15.o ./Source_include/arm_dct4_init_q15.su ./Source_include/arm_dct4_init_q31.cyclo ./Source_include/arm_dct4_init_q31.d ./Source_include/arm_dct4_init_q31.o ./Source_include/arm_dct4_init_q31.su ./Source_include/arm_dct4_q15.cyclo ./Source_include/arm_dct4_q15.d ./Source_include/arm_dct4_q15.o ./Source_include/arm_dct4_q15.su ./Source_include/arm_dct4_q31.cyclo ./Source_include/arm_dct4_q31.d ./Source_include/arm_dct4_q31.o ./Source_include/arm_dct4_q31.su ./Source_include/arm_hamming_f32.cyclo ./Source_include/arm_hamming_f32.d ./Source_include/arm_hamming_f32.o ./Source_include/arm_hamming_f32.su ./Source_include/arm_hamming_f64.cyclo ./Source_include/arm_hamming_f64.d ./Source_include/arm_hamming_f64.o ./Source_include/arm_hamming_f64.su ./Source_include/arm_hanning_f32.cyclo ./Source_include/arm_hanning_f32.d ./Source_include/arm_hanning_f32.o ./Source_include/arm_hanning_f32.su ./Source_include/arm_hanning_f64.cyclo ./Source_include/arm_hanning_f64.d ./Source_include/arm_hanning_f64.o ./Source_include/arm_hanning_f64.su ./Source_include/arm_hft116d_f32.cyclo ./Source_include/arm_hft116d_f32.d ./Source_include/arm_hft116d_f32.o ./Source_include/arm_hft116d_f32.su ./Source_include/arm_hft116d_f64.cyclo ./Source_include/arm_hft116d_f64.d ./Source_include/arm_hft116d_f64.o ./Source_include/arm_hft116d_f64.su ./Source_include/arm_hft144d_f32.cyclo ./Source_include/arm_hft144d_f32.d ./Source_include/arm_hft144d_f32.o ./Source_include/arm_hft144d_f32.su ./Source_include/arm_hft144d_f64.cyclo ./Source_include/arm_hft144d_f64.d ./Source_include/arm_hft144d_f64.o ./Source_include/arm_hft144d_f64.su ./Source_include/arm_hft169d_f32.cyclo ./Source_include/arm_hft169d_f32.d ./Source_include/arm_hft169d_f32.o ./Source_include/arm_hft169d_f32.su ./Source_include/arm_hft169d_f64.cyclo ./Source_include/arm_hft169d_f64.d ./Source_include/arm_hft169d_f64.o ./Source_include/arm_hft169d_f64.su ./Source_include/arm_hft196d_f32.cyclo ./Source_include/arm_hft196d_f32.d ./Source_include/arm_hft196d_f32.o ./Source_include/arm_hft196d_f32.su ./Source_include/arm_hft196d_f64.cyclo ./Source_include/arm_hft196d_f64.d ./Source_include/arm_hft196d_f64.o ./Source_include/arm_hft196d_f64.su ./Source_include/arm_hft223d_f32.cyclo ./Source_include/arm_hft223d_f32.d ./Source_include/arm_hft223d_f32.o ./Source_include/arm_hft223d_f32.su ./Source_include/arm_hft223d_f64.cyclo ./Source_include/arm_hft223d_f64.d ./Source_include/arm_hft223d_f64.o ./Source_include/arm_hft223d_f64.su ./Source_include/arm_hft248d_f32.cyclo ./Source_include/arm_hft248d_f32.d ./Source_include/arm_hft248d_f32.o ./Source_include/arm_hft248d_f32.su ./Source_include/arm_hft248d_f64.cyclo ./Source_include/arm_hft248d_f64.d ./Source_include/arm_hft248d_f64.o ./Source_include/arm_hft248d_f64.su ./Source_include/arm_hft90d_f32.cyclo ./Source_include/arm_hft90d_f32.d ./Source_include/arm_hft90d_f32.o ./Source_include/arm_hft90d_f32.su ./Source_include/arm_hft90d_f64.cyclo ./Source_include/arm_hft90d_f64.d ./Source_include/arm_hft90d_f64.o ./Source_include/arm_hft90d_f64.su ./Source_include/arm_hft95_f32.cyclo ./Source_include/arm_hft95_f32.d ./Source_include/arm_hft95_f32.o ./Source_include/arm_hft95_f32.su ./Source_include/arm_hft95_f64.cyclo ./Source_include/arm_hft95_f64.d ./Source_include/arm_hft95_f64.o ./Source_include/arm_hft95_f64.su ./Source_include/arm_mfcc_f16.cyclo ./Source_include/arm_mfcc_f16.d ./Source_include/arm_mfcc_f16.o ./Source_include/arm_mfcc_f16.su ./Source_include/arm_mfcc_f32.cyclo ./Source_include/arm_mfcc_f32.d ./Source_include/arm_mfcc_f32.o ./Source_include/arm_mfcc_f32.su ./Source_include/arm_mfcc_init_f16.cyclo ./Source_include/arm_mfcc_init_f16.d ./Source_include/arm_mfcc_init_f16.o ./Source_include/arm_mfcc_init_f16.su ./Source_include/arm_mfcc_init_f32.cyclo ./Source_include/arm_mfcc_init_f32.d ./Source_include/arm_mfcc_init_f32.o ./Source_include/arm_mfcc_init_f32.su ./Source_include/arm_mfcc_init_q15.cyclo ./Source_include/arm_mfcc_init_q15.d ./Source_include/arm_mfcc_init_q15.o ./Source_include/arm_mfcc_init_q15.su ./Source_include/arm_mfcc_init_q31.cyclo ./Source_include/arm_mfcc_init_q31.d ./Source_include/arm_mfcc_init_q31.o ./Source_include/arm_mfcc_init_q31.su ./Source_include/arm_mfcc_q15.cyclo ./Source_include/arm_mfcc_q15.d ./Source_include/arm_mfcc_q15.o ./Source_include/arm_mfcc_q15.su ./Source_include/arm_mfcc_q31.cyclo ./Source_include/arm_mfcc_q31.d ./Source_include/arm_mfcc_q31.o ./Source_include/arm_mfcc_q31.su ./Source_include/arm_nuttall3_f32.cyclo ./Source_include/arm_nuttall3_f32.d ./Source_include/arm_nuttall3_f32.o ./Source_include/arm_nuttall3_f32.su ./Source_include/arm_nuttall3_f64.cyclo ./Source_include/arm_nuttall3_f64.d ./Source_include/arm_nuttall3_f64.o ./Source_include/arm_nuttall3_f64.su ./Source_include/arm_nuttall3a_f32.cyclo ./Source_include/arm_nuttall3a_f32.d ./Source_include/arm_nuttall3a_f32.o ./Source_include/arm_nuttall3a_f32.su ./Source_include/arm_nuttall3a_f64.cyclo ./Source_include/arm_nuttall3a_f64.d ./Source_include/arm_nuttall3a_f64.o ./Source_include/arm_nuttall3a_f64.su ./Source_include/arm_nuttall3b_f32.cyclo ./Source_include/arm_nuttall3b_f32.d ./Source_include/arm_nuttall3b_f32.o ./Source_include/arm_nuttall3b_f32.su ./Source_include/arm_nuttall3b_f64.cyclo ./Source_include/arm_nuttall3b_f64.d ./Source_include/arm_nuttall3b_f64.o ./Source_include/arm_nuttall3b_f64.su ./Source_include/arm_nuttall4_f32.cyclo ./Source_include/arm_nuttall4_f32.d ./Source_include/arm_nuttall4_f32.o ./Source_include/arm_nuttall4_f32.su ./Source_include/arm_nuttall4_f64.cyclo ./Source_include/arm_nuttall4_f64.d ./Source_include/arm_nuttall4_f64.o ./Source_include/arm_nuttall4_f64.su ./Source_include/arm_nuttall4a_f32.cyclo ./Source_include/arm_nuttall4a_f32.d ./Source_include/arm_nuttall4a_f32.o ./Source_include/arm_nuttall4a_f32.su ./Source_include/arm_nuttall4a_f64.cyclo ./Source_include/arm_nuttall4a_f64.d
	-$(RM) ./Source_include/arm_nuttall4a_f64.o ./Source_include/arm_nuttall4a_f64.su ./Source_include/arm_nuttall4b_f32.cyclo ./Source_include/arm_nuttall4b_f32.d ./Source_include/arm_nuttall4b_f32.o ./Source_include/arm_nuttall4b_f32.su ./Source_include/arm_nuttall4b_f64.cyclo ./Source_include/arm_nuttall4b_f64.d ./Source_include/arm_nuttall4b_f64.o ./Source_include/arm_nuttall4b_f64.su ./Source_include/arm_nuttall4c_f32.cyclo ./Source_include/arm_nuttall4c_f32.d ./Source_include/arm_nuttall4c_f32.o ./Source_include/arm_nuttall4c_f32.su ./Source_include/arm_nuttall4c_f64.cyclo ./Source_include/arm_nuttall4c_f64.d ./Source_include/arm_nuttall4c_f64.o ./Source_include/arm_nuttall4c_f64.su ./Source_include/arm_rfft_f32.cyclo ./Source_include/arm_rfft_f32.d ./Source_include/arm_rfft_f32.o ./Source_include/arm_rfft_f32.su ./Source_include/arm_rfft_fast_f16.cyclo ./Source_include/arm_rfft_fast_f16.d ./Source_include/arm_rfft_fast_f16.o ./Source_include/arm_rfft_fast_f16.su ./Source_include/arm_rfft_fast_f32.cyclo ./Source_include/arm_rfft_fast_f32.d ./Source_include/arm_rfft_fast_f32.o ./Source_include/arm_rfft_fast_f32.su ./Source_include/arm_rfft_fast_f64.cyclo ./Source_include/arm_rfft_fast_f64.d ./Source_include/arm_rfft_fast_f64.o ./Source_include/arm_rfft_fast_f64.su ./Source_include/arm_rfft_fast_init_f16.cyclo ./Source_include/arm_rfft_fast_init_f16.d ./Source_include/arm_rfft_fast_init_f16.o ./Source_include/arm_rfft_fast_init_f16.su ./Source_include/arm_rfft_fast_init_f32.cyclo ./Source_include/arm_rfft_fast_init_f32.d ./Source_include/arm_rfft_fast_init_f32.o ./Source_include/arm_rfft_fast_init_f32.su ./Source_include/arm_rfft_fast_init_f64.cyclo ./Source_include/arm_rfft_fast_init_f64.d ./Source_include/arm_rfft_fast_init_f64.o ./Source_include/arm_rfft_fast_init_f64.su ./Source_include/arm_rfft_init_f32.cyclo ./Source_include/arm_rfft_init_f32.d ./Source_include/arm_rfft_init_f32.o ./Source_include/arm_rfft_init_f32.su ./Source_include/arm_rfft_init_q15.cyclo ./Source_include/arm_rfft_init_q15.d ./Source_include/arm_rfft_init_q15.o ./Source_include/arm_rfft_init_q15.su ./Source_include/arm_rfft_init_q31.cyclo ./Source_include/arm_rfft_init_q31.d ./Source_include/arm_rfft_init_q31.o ./Source_include/arm_rfft_init_q31.su ./Source_include/arm_rfft_q15.cyclo ./Source_include/arm_rfft_q15.d ./Source_include/arm_rfft_q15.o ./Source_include/arm_rfft_q15.su ./Source_include/arm_rfft_q31.cyclo ./Source_include/arm_rfft_q31.d ./Source_include/arm_rfft_q31.o ./Source_include/arm_rfft_q31.su ./Source_include/arm_svm_linear_init_f32.cyclo ./Source_include/arm_svm_linear_init_f32.d ./Source_include/arm_svm_linear_init_f32.o ./Source_include/arm_svm_linear_init_f32.su ./Source_include/arm_svm_linear_predict_f32.cyclo ./Source_include/arm_svm_linear_predict_f32.d ./Source_include/arm_svm_linear_predict_f32.o ./Source_include/arm_svm_linear_predict_f32.su ./Source_include/arm_svm_polynomial_init_f32.cyclo ./Source_include/arm_svm_polynomial_init_f32.d ./Source_include/arm_svm_polynomial_init_f32.o ./Source_include/arm_svm_polynomial_init_f32.su ./Source_include/arm_svm_polynomial_predict_f32.cyclo ./Source_include/arm_svm_polynomial_predict_f32.d ./Source_include/arm_svm_polynomial_predict_f32.o ./Source_include/arm_svm_polynomial_predict_f32.su ./Source_include/arm_svm_rbf_init_f32.cyclo ./Source_include/arm_svm_rbf_init_f32.d ./Source_include/arm_svm_rbf_init_f32.o ./Source_include/arm_svm_rbf_init_f32.su ./Source_include/arm_svm_rbf_predict_f32.cyclo ./Source_include/arm_svm_rbf_predict_f32.d ./Source_include/arm_svm_rbf_predict_f32.o ./Source_include/arm_svm_rbf_predict_f32.su ./Source_include/arm_svm_sigmoid_init_f32.cyclo ./Source_include/arm_svm_sigmoid_init_f32.d ./Source_include/arm_svm_sigmoid_init_f32.o ./Source_include/arm_svm_sigmoid_init_f32.su ./Source_include/arm_svm_sigmoid_predict_f32.cyclo ./Source_include/arm_svm_sigmoid_predict_f32.d ./Source_include/arm_svm_sigmoid_predict_f32.o ./Source_include/arm_svm_sigmoid_predict_f32.su ./Source_include/arm_welch_f32.cyclo ./Source_include/arm_welch_f32.d ./Source_include/arm_welch_f32.o ./Source_include/arm_welch_f32.su ./Source_include/arm_welch_f64.cyclo ./Source_include/arm_welch_f64.d ./Source_include/arm_welch_f64.o ./Source_include/arm_welch_f64.su

.PHONY: clean-Source_include

